site_name: Looqbox User Guide
nav:
    - Quickstart: index.md
    - Admin: admin-interface
    - R Scripts: r-scripts
    - Cookbook: cookbook
    - Read More: read-more
site_favicon: favicon.ico
repo_url: https://github.com/looqbox/guide
theme: 
  name: cinder
  custom_dir: custom_theme/
extra_css:
    - css/extra.css