site_name: Looqbox User Guide
nav:
    - Quickstart: index.md
    - Admin: Admin-Interface.md
    - R Scripts: R-Scripts.md
    - Cookbook: Cookbook.md
    - Read More: read-more.md
repo_url: https://github.com/looqbox/guide
theme: 
  name: cinder
  custom_dir: custom_theme/
extra_css:
    - css/extra.css
